version: "3.9"

services:
  backend:
    build:
      context: ./backend
    image: crackcode-backend:v1.0.0
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    image: crackcode-frontend:v1.0.0
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
